name: My Config
version: 1.0.0
schema: v1

models:
  - name: Gemini 2.5 Pro
    provider: gemini
    model: gemini-2.5-pro
    apiKey: AIzaSyA7lU4zGYxHkWVy-7r9jJNOnL6bb3I47XU
    roles:
      - chat
      - edit
      - apply

  - name: Gemini 2.5 Flash
    provider: gemini
    model: gemini-2.5-flash
    apiKey: AIzaSyA7lU4zGYxHkWVy-7r9jJNOnL6bb3I47XU
    roles:
      - chat
      - edit

  - name: Gemini 3.1 Flash Lite
    provider: gemini
    model: gemini-3.1-flash-lite-preview
    apiKey: AIzaSyA7lU4zGYxHkWVy-7r9jJNOnL6bb3I47XU
    roles:
      - chat
